# Generated by Django 5.2.4 on 2025-10-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_userprofile_image_serviceimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
    ]
