# Generated by Django 5.2.4 on 2025-10-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_payment_amount_remove_payment_transaction_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='QR', max_length=50),
        ),
    ]
