# Generated by Django 5.2.4 on 2025-10-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_platformaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_ref',
            field=models.FileField(blank=True, null=True, upload_to='transaction_ref/'),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='qr_image',
            field=models.FileField(blank=True, null=True, upload_to='bank_qr/'),
        ),
    ]
