# Generated by Django 5.2.4 on 2025-10-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_order_status_alter_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_manage_order', 'Can manage order')]},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': [('can_approve_payment', 'Can approve payment'), ('can_approve_refund', 'Can approve refund')]},
        ),
    ]
