# Generated by Django 5.2.4 on 2025-10-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_order_options_alter_payment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('manage_order', 'Can manage order')]},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': [('approve_payment', 'Can approve payment'), ('approve_refund', 'Can approve refund')]},
        ),
    ]
