# Generated by Django 5.2.4 on 2025-10-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_review_service_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
    ]
